name = 'justengel_material'
version = '0.0.3'
description = 'Jinja Materializecss theme capability'
url = 'https://github.com/justengel-web/justengel_material'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
